
# MediPredict — AI Health Risk Assessment Platform

## Project Kickoff

### Project Initialization

- **Project Title:** MediPredict — AI Health Risk Assessment Platform
- **Machine Learning Problem Type:** Classification
- **Objective:** Predict whether a patient is at risk of heart disease using patient health data.

### Dataset Information

- **Dataset Name:** Heart Disease Prediction Dataset
- **Dataset Source:** Kaggle
- **Target Variable:** HeartDisease

In [3]:
import pandas as pd
import numpy as np

In [4]:
# Load Dataset
df = pd.read_csv("heart.csv")
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [5]:
# Number of Rows and Columns
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 918
Columns: 12

In [6]:
# Feature Columns
print(df.columns.tolist())

['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS', 'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope', 'HeartDisease']

In [7]:
# Description of Each Feature
feature_description = {
    "Age":"Age of patient",
    "Sex":"Gender",
    "ChestPainType":"Type of chest pain",
    "RestingBP":"Resting blood pressure",
    "Cholesterol":"Serum cholesterol",
    "FastingBS":"Fasting blood sugar",
    "RestingECG":"Resting ECG results",
    "MaxHR":"Maximum heart rate",
    "ExerciseAngina":"Exercise-induced angina",
    "Oldpeak":"ST depression",
    "ST_Slope":"Slope of ST segment",
    "HeartDisease":"Target Variable"
}
pd.DataFrame(feature_description.items(), columns=["Feature","Description"])

           Feature              Description
0              Age           Age of patient
1              Sex                   Gender
2    ChestPainType       Type of chest pain
3        RestingBP   Resting blood pressure
4      Cholesterol        Serum cholesterol
5        FastingBS      Fasting blood sugar
6       RestingECG      Resting ECG results
7            MaxHR       Maximum heart rate
8   ExerciseAngina  Exercise-induced angina
9          Oldpeak            ST depression
10        ST_Slope      Slope of ST segment
11    HeartDisease          Target Variable

## Initial Data Exploration

In [8]:
# First Five Records
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [9]:
# Data Types
df.dtypes

Age                 int64
Sex                object
ChestPainType      object
RestingBP           int64
Cholesterol         int64
FastingBS           int64
RestingECG         object
MaxHR               int64
ExerciseAngina     object
Oldpeak           float64
ST_Slope           object
HeartDisease        int64
dtype: object

In [10]:
# Missing Values
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [11]:
# Summary Statistics
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [12]:
# Identify Numerical and Categorical Features
numerical_features = df.select_dtypes(include=['int64','float64']).columns.tolist()
categorical_features = df.select_dtypes(include=['object']).columns.tolist()

print("Numerical Features:", numerical_features)
print("Categorical Features:", categorical_features)

Numerical Features: ['Age', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'Oldpeak', 'HeartDisease']
Categorical Features: ['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope']

## Project Planning

### Data Preprocessing Steps
- Handle missing values (if any)
- Remove duplicate records
- Encode categorical features
- Split dataset into training and testing sets
- Scale numerical features (if required)

### Feature Engineering
- One-Hot Encoding for categorical variables (if required)

### Planned Machine Learning Algorithms
- Logistic Regression
- Decision Tree
- Random Forest

### Reason for Selection
- Logistic Regression: Baseline classifier
- Decision Tree: Easy to interpret
- Random Forest: Better generalization and accuracy

### Evaluation Metrics
- Accuracy
- Precision
- Recall
- F1-Score
- Confusion Matrix
- ROC-AUC Score